repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3.11
        args: [--line-length=127]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black, --line-length=127]

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
        args: [--max-line-length=127, --max-complexity=18, --ignore=E203,E501,W503]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-python-dateutil, types-pyyaml]
        args: [--ignore-missing-imports, --disallow-untyped-defs, --disallow-incomplete-defs]
        exclude: ^tests/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [yaml, json, markdown, html, css, scss, javascript, typescript, jsx, tsx]
        args: [--write, --prose-wrap=always, --print-width=100]

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []  # Optional: list of Conventional Commits types to allow
