site_name: GLASSPHERE
theme:
  name: readthedocs
plugins:
  - search
  - mkdocstrings
  - git-revision-date-localized
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Infrared Integration: infrared.md
  - Methodology: methodology.md
  - Experimental Setup: experimental-setup.md
  - Data Collection: data-collection.md
  - Analysis Framework: analysis-framework.md
  - API Reference: api.md
  - Divine Law: COVENANT.md
